os:
  - linux
dist: xenial
language: java

services: docker

env:
  global:
    - DOCKER_IMAGE_NAME=thi-rest-bridge
    - DOCKER_REPOSITORY=$DOCKER_USERNAME/$DOCKER_IMAGE_NAME

script:
  - travis_wait 30 ./mvnw package -Pnative -Dquarkus.native.container-build=true || travis_terminate 1;
  - docker build -f src/main/docker/Dockerfile.native -t $DOCKER_IMAGE_NAME . || travis_terminate 1;

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin

deploy:
  provider: script
  script: ./.travis/dockerhub
  on:
    branch: master